export const Types = {
  GOODS_LIST: "GOODS_LIST",
  ADD_TO_CART: "ADD_TO_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  OPEN_ACCOUNT_MODAL: "OPEN_ADD_ACCOUNT_MODAL",
  CLOSE_ACCOUNT_MODAL: "CLOSE_ADD_ACCOUNT_MODAL",
  SELECT_PAYMENT_TYPE: "SELECT_PAYMENT_TYPE",
};