export const Types = {
  GOODS_LIST: "GOODS_LIST",
  ADD_TO_CART: "ADD_TO_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  OPEN_ACCOUNT_MODAL: "OPEN_ADD_ACCOUNT_MODAL",
  CLOSE_ACCOUNT_MODAL: "CLOSE_ADD_ACCOUNT_MODAL",
  SEND_ACCOUNT_DATA: "SEND_ACCOUNT_DATA",
  EDIT_ACCOUNT: "EDIT_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  SELECT_ACCOUNT: "SELECT_ACCOUNT",
  CHANGE_PAYMENT_STEP: "CHANGE_PAYMENT_STEP",
  SELECT_PAYMENT: "SELECT_PAYMENT",
  OPEN_FINAL_MODAL: "OPEN_FINAL_MODAL",
};